# Generated by Django 4.0.4 on 2022-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Header', help_text='<small class="text-muted">this is our header</small><hr><br>', max_length=200, null=True, verbose_name='Header:')),
            ],
            options={
                'verbose_name': 'IceCream Category',
                'verbose_name_plural': 'IceCream Categories',
                'ordering': ('title',),
            },
        ),
    ]
