# Generated by Django 4.0.4 on 2022-06-17 17:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0004_alter_receiptcomment_options_receiptcomment_create_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_student', '0002_city_country_delete_icecreamcategory_city_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Header', help_text='<small class="text-muted">this is our header</small><hr><br>', max_length=250, null=True, verbose_name='Header:')),
                ('image', models.ImageField(blank=True, default='img/receipt/default/default_receipt.jpg', help_text='<small class="text-muted">this is our image</small><hr><br>', null=True, upload_to='img/receipt', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Image:')),
                ('time_to_cook', models.IntegerField(blank=True, default='1', help_text='<small class="text-muted">time needed to cook</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='time needed to cook(in minuts)')),
                ('description', models.TextField(default='Description', help_text='<small class="text-muted">this is our Description</small><hr><br>', verbose_name='Description:')),
                ('author', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">author</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Author off an IceCream')),
                ('ingredients', models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">ingredients</small><hr><br>', to='app_teacher.receiptingredient', verbose_name='IceCream Ingredients')),
            ],
            options={
                'verbose_name': 'IceCream',
                'verbose_name_plural': 'IceCreams',
                'ordering': ('title', 'description'),
            },
        ),
    ]
