# Generated by Django 4.0.4 on 2022-06-17 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_student', '0003_icecream'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Header', help_text='<small class="text-muted">this is our header</small><hr><br>', max_length=250, null=True, verbose_name='Header:')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'IceCream Category',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='IceCreamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, default='Comment', help_text='<small class="text-muted">Comment here</small><hr><br>', max_length=500, null=True, verbose_name='Header:')),
            ],
            options={
                'verbose_name': 'IceCream Comment',
                'verbose_name_plural': 'Comment IceCreams',
                'ordering': ('comment_text',),
            },
        ),
        migrations.CreateModel(
            name='IceCreamIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='Name', help_text='<small class="text-muted">name of an ice-cream</small><hr><br>', null=True, verbose_name='Name:')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IceCreamRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(blank=True, default=False, help_text='<small class="text-muted">Like</small><hr><br>', null=True, verbose_name='Like:')),
                ('rating_value', models.IntegerField(blank=True, default='0', help_text='<small class="text-muted">Mark</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mark')),
            ],
            options={
                'verbose_name': 'IceCream Rate',
                'verbose_name_plural': 'IceCream Rates',
                'ordering': ('IceCream',),
            },
        ),
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('title', 'description'), 'verbose_name': 'IceCream', 'verbose_name_plural': 'IceCream'},
        ),
        migrations.AlterField(
            model_name='icecream',
            name='author',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Author</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Author of an IceCream'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='description',
            field=models.TextField(default='Description', help_text='<small class="text-muted">this is our description</small><hr><br>', verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='time_to_cook',
            field=models.IntegerField(blank=True, default='1', help_text='<small class="text-muted">this is the time needed</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Time needed(in minuts)'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='icecreamrating',
            name='IceCream',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">IceCream</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_student.icecream', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='IceCream'),
        ),
        migrations.AddField(
            model_name='icecreamrating',
            name='user',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">User</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='icecreamcomment',
            name='IceCream',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_student.icecream', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='IceCream'),
        ),
        migrations.AddField(
            model_name='icecreamcomment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">User</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='country_db_column', db_index=True, db_tablespace='country_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Category</small><hr><br>', to='app_student.icecreamcategory', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='IceCream Category'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">Ingredients</small><hr><br>', to='app_student.icecreamingredient', verbose_name='IceCream Ingredients'),
        ),
    ]
