# Generated by Django 4.0.4 on 2022-06-15 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0003_receipt_instructions_alter_receipt_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptcomment',
            options={'ordering': ('-time',), 'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.AddField(
            model_name='receiptcomment',
            name='create',
            field=models.DateTimeField(auto_now_add=True, help_text='<small class="text-muted">время создания</small><hr><br>', null=True, verbose_name='время создания:'),
        ),
        migrations.AddField(
            model_name='receiptcomment',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='<small class="text-muted">время создания</small><hr><br>', null=True, verbose_name='время создания:'),
        ),
        migrations.AddField(
            model_name='receiptcomment',
            name='update',
            field=models.DateTimeField(auto_now=True, help_text='<small class="text-muted">время создания</small><hr><br>', null=True, verbose_name='время создания:'),
        ),
        migrations.AddField(
            model_name='receiptrating',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False, help_text='<small class="text-muted">Лайк</small><hr><br>', null=True, verbose_name='Лайк:'),
        ),
        migrations.AlterField(
            model_name='receiptrating',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_teacher.receipt', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рецепт'),
        ),
    ]
